# Generated by Django 4.0.3 on 2022-09-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cnic',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=25),
        ),
        migrations.DeleteModel(
            name='UserComplaint',
        ),
    ]
