# Generated by Django 4.0.3 on 2022-09-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provder_image', models.ImageField(upload_to='images/')),
                ('providers_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=3000)),
                ('phone_number', models.CharField(max_length=3000)),
                ('address', models.TextField()),
                ('city_address', models.TextField()),
                ('postel_code', models.TextField()),
                ('price', models.TextField()),
                ('order_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myorders', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='providers.providers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=3000)),
                ('phone_number', models.CharField(max_length=3000)),
                ('address', models.TextField()),
                ('city_address', models.TextField()),
                ('postel_code', models.TextField()),
                ('price', models.TextField()),
                ('order_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycustom_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
