# Generated by Django 4.0.3 on 2022-09-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerorders_pakage_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='pakage_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
