# Generated by Django 4.0.3 on 2022-10-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_customorder_pakage_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='city_address',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='pakage_details',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='postel_code',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='price',
        ),
        migrations.AddField(
            model_name='customorder',
            name='city',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='complete_address',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='country',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='order_channel',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='pakage_weight',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='product_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='quantity',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='state',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='customorder',
            name='unit_price',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
